### ISSUE TITLE
Upgrade guide for the Vault operator

### ISSUE THREAD

**Issue by sagikazarmark** [bank-vaults/bank-vaults.dev#107]
We need a place in the documentation for the vault operator at this time, but we will probably need it for other components as well.

- [x] Propose a structure for upgrade guides in the documentation @fekete-robert 
- [x] Review docs PR @ramizpolic 
- [x] Test and document upgrading the vault operator from 1.19 to 1.20 @akijakya 
- [ ] Update Vault Operator upgrade guide in the docs page

**Comment by akijakya** [comment]
Here is a little upgrade guide for review: https://hackmd.io/@DhaVRRKrTnC_nyZMYr-OpA/S18frT4Vp

**Comment by ramizpolic** [comment]
Reviewed @akijakya, please move the upgrade guide to https://bank-vaults.dev/docs/operator/upgrade-vault/

**Comment by ramizpolic** [comment]
@fekete-robert The upgrade guide path is named `upgrade-vault`, can we switch it to just `upgrade`. 
In addition, the contents keep refering to _Upgrade Vault_ even though we are upgrading Vault Operator.
