### ISSUE TITLE
Running the webhook and Vault on different clusters

### ISSUE THREAD

**Issue by nirlevywalkme** [bank-vaults/bank-vaults.dev#117]
The link for the rbac.yaml is wrong - https://github.com/bank-vaults/bank-vaults/raw/main/operator/deploy/rbac.yaml

**Comment by fekete-robert** [comment]
Thanks, we are not entirely finished with migrating the code to the new github organization yet, so a bunch of links are broken right now. I hope to merge some updates next week that will improve the situation, see https://github.com/bank-vaults/bank-vaults.dev/pull/118
