### ISSUE TITLE
Fix Install guide and related resources

### ISSUE THREAD

**Issue by mkoukal** [bank-vaults/bank-vaults.dev#126]
Install guide on [Docsite](https://bank-vaults.dev/docs/operator/) is completely unusable. 
For example it has this code  `kubectl apply -f https://raw.githubusercontent.com/banzaicloud/bank-vaults/master/operator/deploy/rbac.yaml` which returns 404.
Links to helm and operator repo also return 404.

If I try to install operator helm chart directly from repo and then try to  run 
```bash
kubectl apply -f ./deploy/examples/cr.yaml

Error from server (BadRequest): error when creating "./deploy/examples/cr.yaml": 
Vault in version "v1alpha1" cannot be handled as a Vault: strict decoding error: 
unknown field "spec.unsealConfig.options.secretShares", 
unknown field "spec.unsealConfig.options.secretThreshold"
```

If these fields are fixed the PVC is stuck in creation forever.

I think functioning examples for install guide is a must.

**Comment by fekete-robert** [comment]
Hi, we're really sorry for the inconvenience, right now we're in the middle of migrating the repo to a separate github organization, and splitting it into multiple repos for the different components.

@akijakya @ramizpolic can you help @mkoukal on what is the recommended install method right now until we finish migrating the last repo?

**Comment by mkoukal** [comment]
> Hi, we're really sorry for the inconvenience, right now we're in the middle of migrating the repo to a separate github organization, and splitting it into multiple repos for the different components.
> 
> @akijakya @ramizpolic can you help @mkoukal on what is the recommended install method right now until we finish migrating the last repo?

Thanks Robert. I am trying to push the idea of using this operator instead of managing everything by hashicorp helm chart. I appreciate your help a lot.

**Comment by ramizpolic** [comment]
Absolutely, @mkoukal. Feel free to use tagged installation resources from 
1. CRD - https://raw.githubusercontent.com/bank-vaults/vault-operator/v1.20.0/deploy/crd.yaml
2. RBAC - https://raw.githubusercontent.com/bank-vaults/vault-operator/v1.20.0/deploy/rbac.yaml

We will have updated docs today. Apologies for the inconveniences.

**Comment by ramizpolic** [comment]
Absolutely, @mkoukal. Feel free to use tagged installation resources from 
1. RBAC - https://raw.githubusercontent.com/banzaicloud/bank-vaults/v1.15.3/operator/deploy/rbac.yaml
2. CR - https://raw.githubusercontent.com/banzaicloud/bank-vaults/v1.15.3/operator/deploy/cr.yaml

We will have updated docs today. Apologies for the inconveniences.

**Comment by ramizpolic** [comment]
Absolutely, @mkoukal. Feel free to use tagged installation resources from the same repo while we continue working on the migration.

1. RBAC - https://raw.githubusercontent.com/banzaicloud/bank-vaults/v1.15.3/operator/deploy/rbac.yaml
2. CR - https://raw.githubusercontent.com/banzaicloud/bank-vaults/v1.15.3/operator/deploy/cr.yaml

Thank you for understanding!

**Comment by mkoukal** [comment]
thanks @ramizpolic It sort of works, at least it is starting to get deployed. Please consider including in the docs (or editing the `cr.yaml`) how to actually make the PVs. Just uncommenting the section in the yaml file is enough. It is generally good idea to have the simplest possible guide for new onboarding. Although I probably understand the reasons why this section is commented.
The guide IMO could look like this:

1. apply operator helm chart
2. create RBAC
3. create directory on all nodes and give the permissions
4. apply the CR with uncommented PV creation. 
 
But this is just an idea

**Comment by ramizpolic** [comment]
Hi @mkoukal, thank you for suggestions. We will have these items in mind. Note that those are not the most fresh installation resources. We have a release scheduled in the upcoming weeks under new org, so all the docs and resources will be updated by then.

If you have some time, feel free to open a PR and add all the items you deem important. Contributions are always welcome!
