### ISSUE TITLE
Add warning to sign-off commits to project descriptions and PR templates

### ISSUE THREAD

**Issue by sagikazarmark** [bank-vaults/bank-vaults.dev#162]
For some contributors it is not automatic to sign-off their commits which then gets caught by the DCO check which is required and then we need to ask them to do this - maybe we could be more clear about our guidelines about commits e.g. sign-off your commits (`git commit -s`), please use the conventional commits style etc.

**Comment by sagikazarmark** [comment]
Add a note to the contributing guide

**Comment by ramizpolic** [comment]
We could add a bot that will stick a message to PR until the commits have been signed. It will definitely be more informative (rather than just a PR action step red/green indicator).

**Comment by ramizpolic** [comment]
We have a note on the https://bank-vaults.dev/docs/contributing/ guide as well as DCO checks for this.
