### ISSUE TITLE
Update version compatibility matrix between BV products

### ISSUE THREAD

**Issue by ramizpolic** [bank-vaults/bank-vaults.dev#187]
## Overview
I would like to know which version of different BV products (operator, bank-vaults, webhook, reloader, vault-env, etc) are compatible with each other.

## Acceptance criteria
A table summarising all the different combinations of supported versions between products. Indicate the versions that require `v` prefix, and the ones that do not.

## Reference
https://github.com/bank-vaults/vault-operator/blob/main/VERSIONS.md

**Comment by fekete-robert** [comment]
Actually, that's already on the main page of the docs (https://bank-vaults.dev/docs/#version-compatibility-matrix), though I agree that it's not easy to find and maybe we should move it somewhere more visible, maybe to the getting started or the CLI page. What do you think?

**Comment by ramizpolic** [comment]
I think this is a good place for now @fekete-robert. We just need to update it with valid versions

**Comment by fekete-robert** [comment]
Updating the versions in https://github.com/bank-vaults/vault-operator/blob/main/VERSIONS.md and rebuilding the docs should do the trick.

**Comment by ramizpolic** [comment]
closing for the generic ticket
