### ISSUE TITLE
Getting started - test deployment won`t echo actual value of env variable

### ISSUE THREAD

**Issue by MixwelInc** [bank-vaults/bank-vaults.dev#239]
Now even if everything is done right, byte-to-byte with the getting started guide, the test deployment provided in the guide won`t echo actual value of the env variable. If you check the logs of the pod, you will see a blank line, if you check env variables in the pod with "printenv", you will get the vault key from the deployment yaml.
The right way is to check using some script i.e. in python, then it appears to work perfectly fine.

**Comment by csatib02** [comment]
Hey @MixwelInc,

I've already dropped a fix, thanks for reporting.
#240
