### ISSUE TITLE
Annotations doc is outdated

### ISSUE THREAD

**Issue by weichuliu** [bank-vaults/bank-vaults.dev#87]
**Is your feature request related to a problem? Please describe.**

The [Annotations doc](https://banzaicloud.com/docs/bank-vaults/mutating-webhook/annotations/) only listed a subset of the actual supported [annotations](https://github.com/banzaicloud/bank-vaults/blob/f8086b8543ea3ba0ee5e20bbb775ac2302fb2b9c/pkg/webhook/config.go)

Also, the annotations table should contain a support version information. For example, we were using an old version which didn't support `vault-namespace`. And we had to realize it in a hard way.

It will be convenient if people can see the info like `vault-namespace` is supported since version 1.xx.yy, so they know whether they need a new version or not.

**Describe the solution you'd like to see**

Update [annotations.md](https://github.com/banzaicloud/bank-vaults-docs/blob/master/docs/mutating-webhook/annotations.md) to add new annotations that are supported.

Bonus: add a version info to each entry.

**Comment by smarsh-tim** [comment]
I realized this through a difficult path as well, and only discovered by scouring through source.

There are quite a few annotations not documented which are very useful.

**Comment by ramizpolic** [comment]
We covered most of the docs-related issues after the merge. The annotations list should now be complete. If not, feel free to reopen.
